### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by MeikelLP** [ZoserLock/unity-editor-tools#1]

**Comment by ZoserLock** [comment]
Sorry about the late response. Bassically do what ever you want license https://en.wikipedia.org/wiki/WTFPL

**Comment by MeikelLP** [comment]
would be lovely if you would add a `LICENSE` file so Github can pick it up

**Comment by ZoserLock** [comment]
I will do that

**Comment by ZoserLock** [comment]
Submitted on changelist: d6f60c4
